version: "3.1"

services:

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8875:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shatynskyj.entrypoints=websecure"
      - "traefik.http.routers.shatynskyj.rule=Host(`shatynskyj.in.ua`)"
      - "traefik.http.routers.shatynskyj.tls=true"
      - "traefik.http.routers.shatynskyj.tls.certresolver=leresolver"
    networks:
      - traefik-public
    container_name: shatynskyj_nginx

networks:
  traefik-public:
    external: true
