version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8874:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shatynskyj.entrypoints=https"
      - "traefik.http.routers.shatynskyj.rule=Host(`shatynskyj.in.ua`)"
      - "traefik.http.routers.shatynskyj.tls=true"
      - "traefik.http.routers.shatynskyj.tls.certresolver=letsEncrypt"
    networks:
      - proxy
    depends_on:
      - app
    container_name: shatynskyj_nginx

  app:
    image: getaniftywebsite/php:latest
    volumes:
      - ./:/var/www
      - ./_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    user: 1000:1000
    networks:
      - proxy
    container_name: shatynskyj_app

networks:
  proxy:
    external: true



