version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8876:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.shatynskyj.entrypoints=https"
      - "traefik.http.routers.shatynskyj.rule=Host(`shatynskyj.in.ua.localhost`)"
      - "traefik.http.routers.shatynskyj.tls=true"
      - "traefik.http.routers.shatynskyj.tls.certresolver=letsEncrypt"
    networks:
      - proxy
      - default
    depends_on:
      - app
    container_name: shatynskyj_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    user: 1000:1000
    container_name: shatynskyj_app
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8103:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: shatynskyj_db

networks:
  proxy:
    external: true
