version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - /var/www/shatynskyj.in.ua/:/var/www
      - /var/www/shatynskyj.in.ua/_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8081:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.shatynskyj.entrypoints=https"
      - "traefik.http.routers.shatynskyj.rule=Host(`shatynskyj.localhost`)"
      - "traefik.http.routers.shatynskyj.tls=true"
      - "traefik.http.routers.shatynskyj.tls.certresolver=letsEncrypt"
    networks:
      - traefik-public
      - default
    depends_on:
      - app

  app:
    image: getaniftywebsite/php:latest
    volumes:
      - /var/www/shatynskyj.in.ua/:/var/www
      - /var/www/shatynskyj.in.ua/_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - default

networks:
  traefik-public:
    external: true
  default:
