version: "3.1"

services:

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8875:80
    depends_on:
      - app
    container_name: shatynskyj_nginx

  app:
    image: 127.0.0.1:5000/test
    build: .
    volumes:
      - ./:/var/www
    user: 1000:1000
    container_name: shatynskyj_app
    restart: unless-stopped
