version: "3.1"

services:

  nginx:
    image: docker.io/nginx:latest
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8876:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.shatynskyj.entrypoints=websecure"
      - "traefik.http.routers.shatynskyj.rule=Host(`shatynskyj.in.ua`)"
      - "traefik.http.routers.shatynskyj.tls=true"
      - "traefik.http.routers.shatynskyj.tls.certresolver=leresolver"
    networks:
      - traefik-public
    depends_on:
      - app
    container_name: shatynskyj_nginx

  

  app:
    image: thecodingmachine/php:8.1-fpm
    container_name: shatynskyj_app
    networks:
      - traefik-public
    volumes:
      - ./:/var/www
    ports :
    - 9000:9000
    restart: unless-stopped
    depends_on:
    - db
    links:
    - db:db
    environment:
      MYSQL_DB_HOST: db  
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  db:
    image: docker.io/mysql:8.0
    container_name: shatynskyj_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - traefik-public
    restart: unless-stopped
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8103:3306" 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shatynskyj_phpmyadmin
    depends_on:
      - db
    networks:
      - traefik-public
    restart: always
    ports:
      - '8090:80'   
    environment:
      MYSQL_DB_HOST: db  
      MYSQL_USER: root
      MYSQL_PASSWORD: root

networks:
  traefik-public:
    external: true